{{- if .Values.global.isOpenShift }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: {{ template "devfileregistry.name" . }}
  name: {{ template "devfileregistry.fullname" . }}
spec:
  to:
    kind: Service
    name: {{ template "devfileregistry.fullname" . }}
    weight: 100
  port:
    targetPort: 8080
  {{- if .Values.global.tlsEnabled }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end -}}
{{- end -}}